### ISSUE TITLE
How often do you use Airbnb yourself?

### ISSUE THREAD

**Issue by Haroenv** [lencioni/ama#10]

**Comment by lencioni** [comment]
I first used Airbnb in 2012 in Oakland. I had a great experience and never really looked back. I then became a host for 18 months (with the approval of my building's management) and hosted all sorts of interesting people from around the world in my spare bedroom. Then one day, I received a notice from my building's lawyers that I would have to stop hosting within 3 days or I would be evicted. So, I cancelled all of our future guests and stopped hosting.

These days, I stay in Airbnb listings whenever I can while traveling (some places I've visited don't really have any listings, so unfortunately it is not always an option). And, since June this year, we moved out of our apartment and have been living out of Airbnb listings exclusively. We started with a trip to Europe (Stockholm, Amsterdam, Ghent, Bruges, Brussels, Paris) and are currently trying out different neighborhoods in the Bay Area before we settle down again for a while.
